package com.ResearchAgent.AIproject.persistence.dto.enums;

public enum ErrorCodeType {
  VALIDATION_ERROR,
  QUERY_BLANK,
  QUERY_TOO_LONG,
  INVALID_DOMAIN,
  INVALID_DEPTH,
  INVALID_OUTPUT_FORMAT,
  MAX_SOURCES_OUT_OF_RANGE,
  TOO_MANY_TRUSTED_DOMAINS,

  RATE_LIMIT_EXCEEDED,
  CONCURRENT_JOBS_EXCEEDED,

  JOB_NOT_FOUND,
  REPORT_NOT_FOUND,
  JOB_NOT_OWNED,

  SEARCH_RETURNED_NO_RESULTS,
  INSUFFICIENT_SOURCES_SCRAPED,
  ALL_SOURCES_BLOCKED,
  PIPELINE_TIMEOUT,
  DUPLICATE_QUERY_PENDING,

  SEARCH_SERVICE_UNAVAILABLE,
  LLM_SERVICE_UNAVAILABLE,
  LLM_RATE_LIMIT_EXHAUSTED,

  INTERNAL_SERVER_ERROR,
  DATABASE_ERROR,
  CACHE_ERROR
}
